export enum Icons {
  None = '',
  User = 'faUser',
  Google = 'faGoogle',
  Microsoft = 'faMicrosoft',
  Apple = 'faApple',
  ClipBoard = 'faClipboard',
  BorderAll = 'faBorderAll',
  Home = 'faHome',
  ChevronLeft = 'faChevronLeft',
  Trello = 'faTrello',
  Plus = 'faPlus',
  ChevronDown = 'faChevronDown',
  Heart = 'faHeart',
  Users = 'faUsers',
  Settings = 'faScrewdriver',
  Search = 'faSearch',
}
