export enum Icons {
  None = '',
  Apple = 'faApple',
  ArrowRight = 'faArrowRight',
  BorderAll = 'faBorderAll',
  CheckSquare = 'faCheckSquare',
  ChevronDown = 'faChevronDown',
  ChevronLeft = 'faChevronLeft',
  ClipBoard = 'faClipboard',
  Clock = 'faClock',
  EllipsisH = 'faEllipsisH',
  EllipsisV = 'faEllipsisV',
  Google = 'faGoogle',
  Heart = 'faHeart',
  Home = 'faHome',
  Microsoft = 'faMicrosoft',
  PaperClip = 'faPaperclip',
  Paste = 'faPast',
  Plus = 'faPlus',
  Search = 'faSearch',
  Settings = 'faScrewdriver',
  Tag = 'faTag',
  Tags = 'faTags',
  Times = 'faTimes',
  Trello = 'faTrello',
  User = 'faUser',
  Users = 'faUsers',
}
